### ISSUE TITLE
Linking subjects to a subject set

### ISSUE THREAD

**Issue by tjayasinghe** [zooniverse/panoptes-subject-uploader#22]
I am bringing this issue up in reference to something I encountered when uploading a subject set of 53k images. I started the upload (not breaking it up into batches- I shouldn't have done this!) and the upload went on until it reached the 24k image mark. Unfortunately, the panoptes-subject-uploader encountered a timeout error and the upload was halted. When this happened, NONE of the 24k images were linked to the subject set.
I was thinking that perhaps it would be a good idea if the script can link subjects as the upload progresses rather than linking everything at the end of the upload. This would alleviate problems like the one I encountered above!

Thank you,
TJ

**Comment by srallen** [comment]
@mwp-tj Are you on the latest version of the client? There have been a few bug fixes and we added functionality to reattempt http requests every 5 seconds up to 5 times just recently. The latest version is 1.3.0. If this happened on the latest version, could you share the log file so we can take a look at the error?

As for subject set linking, we have to do it at the end so that the API routes are used in a optimized way that won't cause an overload. If a particular subject does fail, now after the five attempts, what should happen is that the subject is deleted, the creation and upload process will continue on and the remaining subjects will be linked to the subject-set. Again, if this doesn't happen, please share the error log file so we can take a look.

**Comment by srallen** [comment]
Going to close for now. Will reopen if there is more information from a log file.
