### ISSUE TITLE
Flag to skip file upload

### ISSUE THREAD

**Issue by srallen** [zooniverse/panoptes-subject-uploader#7]
Add a flag to skip file upload and only parse manifest. This is for projects that have images hosted elsewhere and are specifying URLs in the manifest.

**Comment by simensta** [comment]
@srallen and I discussed incorporating the following to resolve this issue:
- [x] 1. Add an explicit flag to skip file upload
- [x] 2. Verify that the image URL in the manifest returns a 200 status code
- [x] 3. Verify that the image URL specifies https
- [ ] 4. Any failures due to 2 or 3 should be noted in an error log, once Issue#8 is resolved.
